RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :links
  
  resources :posts, except: [:index]
  
  resources :subs, except: :destroy
  
  
end

RedditOnRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditOnRails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  validates :subs, length: { minimum: 1 }
  
  # belongs_to :sub,
  # foreign_key: :sub_id,
  # class_name: :Sub
  
  belongs_to :author, 
  foreign_key: :user_id,
  class_name: :User
  
  has_many :post_subs,
  foreign_key: :post_id,
  class_name: :PostSub,
  inverse_of: :post
  
  has_many :subs, 
  through: :post_subs,
  source: :sub
  
  
end

RedditOnRails/app/models/post_sub.rb
class PostSub < ApplicationRecord
  
  belongs_to :post,
    foreign_key: :post_id,
    class_name: :Post
  
  belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub
  
end

RedditOnRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true 
  validates :title, uniqueness: true
  
  belongs_to :moderator, 
  foreign_key: :user_id,
  class_name: :User
  
  # has_many :posts, 
  # foreign_key: :sub_id,
  # class_name: :Post,
  # dependent: :destroy
  
  has_many :sub_posts, 
  foreign_key: :sub_id,
  class_name: :PostSub,
  dependent: :destroy,
  inverse_of: :post
  
  has_many :posts,
  through: :sub_posts, 
  source: :post
  
  
end

RedditOnRails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}
  
  attr_reader :password
  
  after_initialize :ensure_session_token
  
  has_many :subs,
  foreign_key: :user_id,
  class_name: :Sub 
  
  has_many :posts,
  foreign_key: :user_id,
  class_name: :Post,
  dependent: :destroy
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end
  
  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
  
  def self.find_by_credentials(username, pw)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(pw)
    user
  end
  
end

RedditOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user, :logged_in?
  
  def login(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end  
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
  
  def logout
    current_user.reset_session_token
    session[:session_token] = nil
    @current_user = nil 
    redirect_to new_session_url
  end
end

RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  
  def new 
    @subs = Sub.all
    @post = Post.new 
    @sub_id = params[:sub_id]
    render :new
  end 
  
  def create 
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    

    if @post.save 

      redirect_to post_url(@post)
    else 
      flash.now[:errors] = @post.errors.full_messages 
      render :new
    end
  end 
  
  def edit 
    @subs = Sub.all
    @post = Post.find(params[:id])
    render :edit
  end 
  
  def update 
    @post = Post.find(params[:id])
    
    unless @post.author == current_user
      flash[:errors] = ['You are not the author of this post']
      redirect_to post_url(@post)
    end
    
    if @post.update(post_params)
      redirect_to post_url(@post)
    else 
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end 
  
  
  def show 
    @post = Post.find(params[:id])
    render :show
  end
  
  def destroy 
    @post = Post.find(params[:id])
    sub_id = @post.sub_id
    @sub = Sub.find(sub_id)
    @post.destroy
    redirect_to sub_url(@sub)
  end
  
  private 
  
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

RedditOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    # debugger
    username = params[:user][:username]
    password = params[:user][:password]
    @user = User.find_by_credentials(username, password)
    if @user 
      login(@user)
      redirect_to subs_url
    else
      @user = User.new
      flash.now[:errors] = 'Invalid Login Credentials'
      render :new 
    end
  end
  
  def destroy
    logout
  end
  
end

RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_login
  
  def new
    @sub = Sub.new
    render :new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
    
  end
  
  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end
  
  def update
    @sub = Sub.find(params[:id])
    
    unless @sub.moderator == current_user
      flash[:errors] = ['You are not the owner of this sub']
      redirect_to subs_url
    end
    
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @sub = Sub.find(params[:id])
    
    unless @sub.moderator == current_user
      flash[:errors] = ['You are not the owner of this sub']
      redirect_to subs_url
    end
    
    @sub.destroy
    redirect_to subs_url
  end
  
  def index
    @subs = Sub.all
    render :index
  end
  
  def show
    @sub = Sub.find(params[:id])
    render :show
  end
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
end

RedditOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditOnRails/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" 
    name=\"authenticity_token\" 
    value=\"<%= form_authenticity_token%>\">".html_safe
  end
end

RedditOnRails/app/helpers/links_helper.rb
module LinksHelper
end

RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

RedditOnRails/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditOnRails/app/helpers/subs_helper.rb
module SubsHelper
end

RedditOnRails/app/helpers/users_helper.rb
module UsersHelper
end

RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= flash[:errors] %>
      <% if logged_in? %>
        <h2> Welcome: <%= current_user.username %></h2>
        <form class="" action="<%= session_url %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" name="" value="Log Out">
        </form>
        
        <form class="" action="<%= subs_url %>" method="get">
          <%= auth_token %>
          <input type="submit" value="View Subs">
        </form>
      <% else %>
      
        <form class="" action="<%= new_session_url %>" method="get">
          <%= auth_token %>
          <input type="submit" name="" value="Sign In">
        </form>
        
        <form class="" action="<%= new_user_url %>" method="get">
          <%= auth_token %>
          <input type="submit" name="" value="Sign Up">
        </form>
      
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

RedditOnRails/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form class="" action="<%= post_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>Title 
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <br>
  <label>URL 
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <br>
  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>
  
  <input type="hidden" name="post[sub_ids][]" value="">
  <% @subs.each do |sub| %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %>
    <br>
  <% end %>
  
  <input type="submit" value="Edit Post">
</form>

RedditOnRails/app/views/posts/new.html.erb
<h1>New Post Page</h1>

<form class="" action="<%= posts_url %>" method="post">
  <%= auth_token %>
  <label>Title 
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <br>
  <label>URL 
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <br>
  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>
  <input type="hidden" name="post[sub_ids][]" value="">
  <% @subs.each do |sub| %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %>
    <br>
  <% end %>
  
  <input type="submit" value="Create New Post">
</form>

RedditOnRails/app/views/posts/show.html.erb
<h1>Post Show Page</h1>

<ul>
  <li>
    Title: <%= @post.title %>
  </li>
  <li>
    URL: <%= @post.url %>
  </li>
  <li>
    Content: <%= @post.content %>
  </li>
</ul>

<form class="" action="<%= edit_post_url %>" method="get">
  <%= auth_token %>
  <input type="submit"  value="Edit Post">
</form>

RedditOnRails/app/views/subs/index.html.erb
<h1>Subs Index Page</h1>
<% @subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
  <br>
<% end %>

<form class="" action="<%= new_sub_url %>" method="get">
  <%= auth_token %>
  <input type="submit" name="" value="Create Sub">
  
</form>

RedditOnRails/app/views/subs/new.html.erb
<h1>New Subs Page</h1>
<form action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description
    <textarea name="sub[description]" rows="8" cols="80"></textarea>
  </label>
  <input type="submit" value="Create New Sub">
</form>

RedditOnRails/app/views/subs/show.html.erb
<h1>Show Sub Page</h1>

<% @sub.posts.each do |post| %>
  <a href="<%= post_url(post) %>"><%= post.title %></a>
  <br>
<% end %>

<form class="" action="<%= new_post_url %>" method="get">
  <%= auth_token %>
  <input type="submit" name="" value="Create Post">
</form>

RedditOnRails/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

RedditOnRails/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  
  
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  
  <input type="submit" name="" value="Sign Up">
  
</form>